services:
  app:
    deploy:
      resources:
        limits:
          memory: 1G
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CINCEL_DATA_SOURCE: ${NEXT_PUBLIC_CINCEL_DATA_SOURCE:-localstorage}
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL:-}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY:-}
    ports:
      - "3000:3000"
    env_file:
      - .env
